# Generated by Django 3.1.4 on 2020-12-06 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('column_separator', models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)')], default=',', max_length=1)),
                ('string_character', models.CharField(choices=[("'", "Quotation mark (')"), ('"', 'Double quotation mark (")')], default='"', max_length=1)),
                ('modified', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=40)),
                ('column_type', models.CharField(choices=[('FN', 'Full name'), ('INT', 'Integer'), ('CO', 'Company'), ('JB', 'Job'), ('DM', 'Domain')], max_length=40)),
                ('integer_from', models.IntegerField(blank=True)),
                ('integer_to', models.IntegerField(blank=True)),
                ('order', models.SmallIntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker.schema')),
            ],
        ),
    ]
