# Generated by Django 3.1.4 on 2020-12-07 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0002_auto_20201207_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(choices=[('FN', 'Full name'), ('INT', 'Integer'), ('CO', 'Company'), ('JB', 'Job'), ('DM', 'Domain')], max_length=40)),
                ('integer_from', models.IntegerField(blank=True, null=True)),
                ('integer_to', models.IntegerField(blank=True, null=True)),
                ('order', models.SmallIntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker.schema')),
            ],
        ),
        migrations.DeleteModel(
            name='ColumnNames',
        ),
    ]
