# Generated by Django 3.1.4 on 2020-12-07 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0003_auto_20201207_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='integer_to',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='column',
            old_name='integer_from',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='column',
            name='column_name',
        ),
        migrations.AddField(
            model_name='column',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('FN', 'Full name'), ('INT', 'Integer'), ('CO', 'Company'), ('JB', 'Job'), ('DM', 'Domain')], default='FN', max_length=40),
            preserve_default=False,
        ),
    ]
