# Generated by Django 3.1.4 on 2020-12-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0004_auto_20201207_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
