# Generated by Django 3.1.4 on 2020-12-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0007_auto_20201212_1319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('schema', 'order')},
        ),
        migrations.AlterIndexTogether(
            name='column',
            index_together=set(),
        ),
    ]
