# Generated by Django 3.1.4 on 2020-12-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0008_auto_20201212_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['order']},
        ),
    ]
